### ISSUE TITLE
Thoughts on serialize/deserialize?

### ISSUE THREAD

**Issue by bitmage** [Factisio/factis-store-hexastore#1]
Thinking about serialization to support persistence in a key/value store or transferring/synchronizing state over the wire.

Serialize:

``` javascript
JSON.stringify(f.hexastore.queryXXX(null, null, null))
```

Deserialize:

``` javascript
var f = new Factis();
var list = JSON.parse('[["Factis","is","nice",true],["Factis","is","fast",true]]');

var facts = list.map(function(i) {
  this.f.fact.apply(f, i);
});

f.add(facts);
```
1.  Should these be a part of the standard API?
2.  Where would you like them?
3.  Can you think of a more performant or optimal way to do this, or does this seem nice?

Happy to submit a pull request.

**Comment by crubier** [comment]
Done, 

You should now be able to import and export to strings as explained on http://factis.io:

```
var myExportString = f.hexastore.exportString();
f.hexastore.importString(myExportString);
```

There are also methods to export to files of different formats when used within node.js. These functions are not yet documented because i did not test them properly yet. Here they are:

`exportJSON` and `importJSON` for json files
`exportZip` and `importZip` for json files compressed in a zip file
`exportNt` and `importNt` for NT files (basic support)

Let me know if there are any problems.

**Comment by bitmage** [comment]
Interesting solution!  I like it.  I didn't at first glance realize that you already have all the data you need to regenerate all indexes from just the SPO property.  Neat!
